language: node_js

node_js:
  - "lts/carbon"
  - "lts/dubnium"
  - "11"
  - "12"

dist: xenial
cache: npm

matrix:
  fast_finish: true
  include:
    - node_js: lts/carbon
    - node_js: lts/dubnium
  allow_failures:
    - node_js: "11"
    - node_js: "12"

script:
  - npm run test:ci
  - npm run build

jobs:
  include:
    - stage: doctoc-check
      install: npm install -g doctoc
      if: type = pull_request OR branch = master
      script:
        - cp README.md README.md.orig
        - npm run doctoc
        - diff -q README.md README.md.orig
      node_js: lts/carbon
