language: node_js
dist: trusty
node_js:
  - 6
  - 7
  - lts/boron
env:
  - CXX=g++-4.8
cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"
